project:
  type: website

website:
  title: "SG Bus Commute Pattern"
  page-navigation: true
  
  navbar:
    left:
    - text: "Overview"
      href: "Overview/Project_Proposal.html"
    - text: "User Guide"
      href: "Userguide/VAA_Group10_UserGuide.pdf"
    - text: "Application"
      href: "https://3vm3r5-da-huo.shinyapps.io/Visual-Project/?_ga=2.139833585.395284405.1680390288-1164590008.1680258801"
    - text: "Poster"
      href: "Poster/VAA_Poster_Team1.pdf"
      
    
    right:
    - icon: github
      href: "https://github.com/IvoryHuo/Visual-Project/tree/IvoryHuo-patch-1"
    - text: "The Team" 
      href: Team.qmd


format:
  html:
    theme: Journal
    css: styles.css
    toc: true

editor: visual