project:
  type: website

website:
  navbar:
    left:
    - text: "Overview"
      menu: 
        - text: "Project Proposal"
          href: "Overview/Project_Proposal.html"
        - text: "Team"
          
    
    - text: "Application"
      menu:
      - text: "User Guide"
      - text: "Shiny Application"
        

    
    
    right:
      - href: index.qmd
        text: Home


format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual