project:
  type: website

website:
  title: "Singapore Bus Commute Pattern"
  page-navigation: true
  
  navbar:
    left:
    - text: "Overview"
      href: "Overview/Project_Proposal.html"
    - text: "User Guide"
      href: "Userguide/VAA_Group1_UserGuide.pdf"
    - text: "Application"
      href: "https://3vm3r5-da-huo.shinyapps.io/Visual-Project/?_ga=2.139833585.395284405.1680390288-1164590008.1680258801"
    - text: "Poster"
      
    
    right:
    - text: "Team"
      href: "Team.html"
    - href: index.qmd
      text: Home


format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual